# CHAPTER 03 넘파이

## 01 넘파이란?

### 1. 넘파이의 개념

▪ 파이썬의 고성능 과학 계산용 라이브러리  
▪ 벡터나 행렬 같은 선형대수의 표현법을 코드로 처리  
▪ 사실상의 표준 라이브러리  
▪ 다차원 리스트나 크기가 큰 데이터 처리에 유리  

### 2. 넘파이의 특징

▪ 속도가 빠르고 메모리 사용이 효율적  
- 데이터를 메모리에 할당하는 방식이 기존과 다름  

▪ 반복문을 사용하지 않음  
- 연산할 때 병렬로 처리  
- 함수를 한 번에 많은 요소에 적용
  
▪ 다양한 선형대수 관련 함수 제공    
▪ C, C++, 포트란 등 다른 언어와 통합 사용 가능  

## 02 넘파이 배열 객체 다루기

### 1. 넘파이 배열과 텐서

▪ 넘파이 배열(ndarray) : 넘파이에서 텐서 데이터를 다루는 객체  

▪ 텐서(tensor) : 선형대수의 데이터 배열  
- 랭크(rank)에 따라 이름이 다름

### 2. 배열의 메모리 구조

▪ 배열 생성
- np.array 함수 사용하여 배열 생성

In [165]:
import numpy as np
test_array = np.array([1, 4, 5, 8], float)
# 매개변수 1: 배열 정보
# 매개변수 2: 넘파이 배열로 표현하려는 데이터 타입

• 파이썬 리스트와 넘파이 배열의 차이점  
- 텐서 구조에 따라 배열 생성
    - 배열의 모든 구성 요소에 값이 존재해야 함

In [166]:
import numpy as np
test_list = [[1, 4, 5, 8], [1, 4, 5]]
np.array(test_list, float) # ValueError

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

▪ 동적 타이핑을 지원하지 않음
- 하나의 데이터 타입만 사용  

▪ 데이터를 메모리에 연속적으로 나열
- 각 값 메모리 크기가 동일
- 검색이나 연산 속도가 리스트에 비해 훨씬 빠름

In [35]:
import numpy as np

In [36]:
test_array = np.array([1, 4, 5, 8], float)
test_array

array([1., 4., 5., 8.])

In [37]:
type(test_array[3])

numpy.float64

### 3. 배열의 생성

In [38]:
# 배열을 실수형으로 선언
# 배열을 출력해보면 값이 모두 실수형
test_array = np.array([1, 4, 5, "8"], float)
print(test_array)

[1. 4. 5. 8.]


In [39]:
# - 데이터 특징을 출력하는 요소(property)는 dtype과 shape
# - dtype은 넘파이 배열의 데이터 타입을 반환
# - shape는 넘파이 배열에서 객체(object)의 차원(dimension)에 대한 구성 정보를 반환

In [40]:
print(type(test_array[3])) # 실수형(floating Type)으로 자동 형 변환 실시

<class 'numpy.float64'>


In [41]:
print(test_array.dtype) # 배열 전체의 데이터 타입 반환

float64


In [42]:
print(test_array.shape) # 배열의 구조(shape)를 반환함

(4,)


### 3.1 배열의 구조(shape)

In [43]:
matrix = [[1,2,5,8], [1,2,5,8], [1,2,5,8]]
np.array(matrix, int).shape

(3, 4)

In [44]:
tensor_rank3 = [
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]
]
np.array(tensor_rank3, int).shape

(4, 3, 4)

In [ ]:
tensor_rank3 = [[[1, 2, 5, 8], [1, 2, 5, 8], [1, 2,
5, 8]], [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
[[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],[[1, 2,
5, 8], [1, 2, 5, 8], [1, 2, 5, 8]] ]
np.array(tensor_rank3, int).ndim # 차원

3

In [46]:
np.array(tensor_rank3, int).size

48

### 3.2 dtype

▪ 매개변수 dtype으로 넘파이 배열의 데이터 타입 지정
- 변수가 사용하는 메모리 크기가 정해짐

In [47]:
np.array( [ [1, 2, 3.5], [4, 5, 6.5]], dtype=int)

array([[1, 2, 3],
       [4, 5, 6]])

- dtype을 실수형인 float으로 지정한다면 모든 데이터가 실수형으로 저장되는 것을 확인 가능

In [48]:
np.array( [ [1, 2, 3.5], [4, 5, 6.5]], dtype=float)

array([[1. , 2. , 3.5],
       [4. , 5. , 6.5]])

In [50]:
import sys

In [ ]:
np.array( [[1, 2, 3.5], [4, 5, 6.5]],
dtype=np.float64).itemsize # ‐ np.float64로 dtype을 선언하면 64비트, 즉 8바이트 차지

8

In [ ]:
np.array( [[1, 2, 3.5], [4, 5, 6.5]],
dtype=np.float32).itemsize # ‐ np.float32로 dtype을 선언하면 32비트, 즉 4바이트 차지

4

### 4. 배열의 구조 다루기

▪ rehape 함수로 배열의 구조를 변경하고 랭크를 조절

In [54]:
x = np.array([[1, 2, 5, 8], [1, 2, 5, 8]])
x.shape

(2, 4)

In [55]:
x.reshape(-1,)

array([1, 2, 5, 8, 1, 2, 5, 8])

- 반드시 전체 요소의 개수는 통일

In [ ]:
x = np.array(range(8))
x.reshape(2,2)

ValueError: cannot reshape array of size 8 into shape (2,2)

- -1을 사용하면 나머지 차원의 크기를 지정했을 때 전체 요소의 개수를 고려하여 마지막 차원이 자동으로 지정됨

In [ ]:
x = np.array(range(8)).reshape(4,2)
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [ ]:
x.reshape(2,-1)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
x.reshape(2,2,-1)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

▪ flatten 함수는 데이터 그대로 1차원으로 변경
- 데이터의 개수는 그대로 존재
- 배열의 구조만 변한다

In [ ]:
x = np.array(range(8)).reshape(2,2,2)
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
x.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

### 5. 인덱싱과 슬라이싱

### 5.1 인덱싱

▪ 인덱싱(indexing) : 리스트에 있는 값의 상대적인 주소 (offset)로 값에 접근  

▪ 넘파이 배열의 인덱스 표현에는 ‘,’을 지원  
- ‘[행][열]’ 또는 ‘[행,열]’ 형태  

▪ 3차원 텐서 이상은 shape에서 출력되는 랭크 순서대로 인덱싱에 접근  

In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6]], int)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
x[0][0]

np.int64(1)

In [ ]:
x[0,2]

np.int64(3)

In [ ]:
x[0, 1] = 100
x

array([[  1, 100,   3],
       [  4,   5,   6]])

### 5.2 슬라이싱

- 슬라이싱(slicing) : 인덱스를 사용하여 리스트 일부를 잘라내어 반환  
- 넘파이 배열은 행과 열을 나눠 슬라이싱할 수 있음

In [57]:
x = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], int)
x[:,2:] # 전체 행의 2열 이상

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [58]:
x[1,1:3] # 1행의 1열 ~ 2열

array([7, 8])

In [59]:
x[1:3] # 1행 ~ 2행의 전체

array([[ 6,  7,  8,  9, 10]])

▪ 증가값(step) : 리스트에서 데이터의 요소를 호출할 때 데이터를 건너뛰면서 반환  
- ‘[시작 인덱스:마지막 인덱스:증가값]’ 형태  
- 각 랭크에 있는 요소별로 모두 적용할 수 있음  

In [62]:
x = np.array(range(15), int).reshape(3, -1)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [66]:
x[:, ::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14]])

In [67]:
x[::2, ::3]

array([[ 0,  3],
       [10, 13]])

### 6. 배열 생성 함수

### 6.1 arange

▪ range 함수와 같이 차례대로 값을 생성    
▪ ‘(시작 인덱스, 마지막 인덱스, 증가값)’으로 구성    
▪ range 함수와 달리 증가값에 실수형이 입력되어도 값을 생성할 수 있음   
▪ 소수점 값을 주기적으로 생성할 때 유용

In [68]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
np.arange(-5, 5)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [70]:
np.arange(0, 5,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

### 6.2 ones, zeros, empty

▪ ones 함수 : 1로만 구성된 넘파이 배열을 생성  
- 사전에 shape 값을 넣어서 원하는 크기의 넘파이 배열 생성  

▪ zeros 함수 : 0으로만 구성된 넘파이 배열을 생성  

▪ empty 함수 : 활용 가능한 메모리 공간 확보하여 반환  
- ones와 zeros는 먼저 shape의 크기만큼 메모리를 할당하고 그곳에 값을 채움  
- 해당 메모리 공간에 값이 남았을 경우 그 값을 함께 반환  
- empty는 메모리 초기화 않아 생성될 때마다 다른 값 반환    

▪ 생성 시점에서 dtype을 지정해주면 해당 데이터 타입으로 배열 생성  

In [80]:
np.ones(shape=(5,2), dtype=np.int8)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int8)

In [78]:
np.zeros(shape=(2,2), dtype=np.float32)

array([[0., 0.],
       [0., 0.]], dtype=float32)

In [81]:
np.empty(shape=(2,4), dtype=np.float32)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)

### 6.3 ones_like, zeros_like, empty_like

▪ ones_like 함수 : 기존 넘파이 배열과 같은 크기로 만들어 내용을 1로 채움  
▪ zeros_like 함수 : 기존 넘파이 배열과 같은 크기로 만들어 내용을 0으로 채움  
▪ empty_like 함수 : 기존 넘파이 배열과 같은 크기로 만들어 빈 상태로 만듦

In [82]:
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [83]:
np.ones_like(x)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [84]:
np.zeros_like(x)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### 6.4 identity, eye, diag

▪ identity 함수 : 단위행렬(i행렬)을 생성  
- 매개변수 n으로 n×n 단위행렬을 생성

In [85]:
np.identity(n=3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [86]:
np.identity(n=4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

▪ eye 함수 : 시작점과 행렬 크기를 지정, 단위행렬 생성  
- N은 행의 개수, M은 열의 개수를 지정  
- k는 열의 값을 기준으로 시작 인덱스

In [87]:
np.eye(N=3, M=5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [88]:
np.eye(N=3, M=5, k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

▪ diag 함수 : 행렬의 대각성분 값을 추출

In [89]:
matrix = np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [90]:
np.diag(matrix)

array([0, 4, 8])

In [91]:
np.diag(matrix, k=1)

array([1, 5])

### 7. 통계 분석 함수

▪ uniform 함수 : 균등분포 함수  
- ‘np.random.uniform(시작값, 끝값, 데이터개수)’

In [92]:
np.random.uniform(0, 5, 10)

array([0.58834532, 3.67074453, 0.67009781, 4.81520156, 3.95794589,
       2.26107447, 3.86941801, 4.98906242, 2.67651532, 0.66161216])

▪ normal 함수 : 정규분포 함수
- ‘np.random.normal(평균값, 분산, 데이터개수)’

In [93]:
np.random.normal(0, 2, 10)

array([ 3.54288676, -2.92985803,  1.60629337, -0.00642769, -1.30483405,
       -0.6363319 , -0.6620718 ,  1.18201831,  3.43309997, -0.3536378 ])

## 03 넘파이 배열 연산

### 1. 연산 함수

▪ 연산 함수(operation function) : 배열 내부 연산을 지원하는 함수  
▪ 축(axis) : 배열의 랭크가 증가할 때마다 새로운 축이 추가되어 차원 증가  
▪ sum 함수 : 각 요소의 합을 반환

In [94]:
import numpy as np
test_array = np.arange(1, 11)
test_array.sum()

np.int64(55)

- sum 함수를 랭크가 2 이상인 배열에 적용할 때 축으로 연산의 방향을 설정

In [95]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [96]:
test_array.sum(axis=0)

array([15, 18, 21, 24])

In [97]:
test_array.sum(axis=1)

array([10, 26, 42])

In [99]:
test_array = np.arange(1, 13).reshape(3, 4)
third_order_tensor = np.array([test_array,test_array, test_array])
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [100]:
third_order_tensor.sum(axis=0)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

In [101]:
third_order_tensor.sum(axis=1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [102]:
third_order_tensor.sum(axis=2)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [103]:
test_array = np.arange(1, 13).reshape(3, 4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [104]:
test_array.mean(axis=1) # axis=1 축을 기준으로 평균 연산

array([ 2.5,  6.5, 10.5])

In [105]:
test_array.std() # 전체 값에 대한 표준편차 연산

np.float64(3.452052529534663)

In [107]:
test_array.std(axis=0) # axis=0 축을 기준으로 표준편차 연산

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [108]:
np.sqrt(test_array) # 각 요소에 제곱근 연산 수행

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

### 2. 연결 함수

▪ 연결 함수(concatenation functions) : 두 객체 간의 결합을 지원하는 함수  
▪ vstack 함수 : 배열을 수직으로 붙여 하나의 행렬을 생성  
▪ hstack 함수 : 배열을 수평으로 붙여 하나의 행렬을 생성  
- 넘파이는 열 벡터를 표현할 수 없어 2차원 행렬 형태로 표현

In [109]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
np.vstack((v1, v2))

array([[1, 2, 3],
       [4, 5, 6]])

In [110]:
np.hstack((v1,v2))

array([1, 2, 3, 4, 5, 6])

In [111]:
v1 = v1.reshape(-1, 1)
v2 = v2.reshape(-1, 1)
v1

array([[1],
       [2],
       [3]])

In [113]:
v2

array([[4],
       [5],
       [6]])

In [114]:
np.hstack((v1,v2))

array([[1, 4],
       [2, 5],
       [3, 6]])

▪ concatenate 함수 : 축을 고려하여 두 개의 배열을 결합  
- 스택(stack) 계열의 함수와 달리 생성될 배열과 소스가 되는 배열의 차원이 같아야 함  
- 두벡터를 결합하고 싶다면, 해당 벡터를 일단 2차원 배열 꼴로 변환 후 행렬로 나타내야 함  

In [115]:
v1 = np.array([[1, 2, 3]])
v2 = np.array([[4, 5, 6]])
np.concatenate((v1,v2), axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [116]:
v1 = np.array([1, 2, 3, 4]).reshape(2,2)
v2 = np.array([[5,6]]).T
v1

array([[1, 2],
       [3, 4]])

In [118]:
v2

array([[5],
       [6]])

In [119]:
np.concatenate((v1,v2), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

### 3. 사칙연산 함수

▪ 넘파이는 파이썬과 동일하게 배열 간 사칙연산 지원  
- 행렬과 행렬, 벡터와 백터 간 사칙연산이 가능  

▪ 같은 배열의 구조일 때 요소별 연산(element-wise operation)
- 요소별 연산 : 두 배열의 구조가 동일할 경우 같은 인덱스 요소들끼리 연산

In [120]:
x = np.arange(1, 7).reshape(2,3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [121]:
x + x

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [122]:
x - x

array([[0, 0, 0],
       [0, 0, 0]])

In [123]:
x / x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [124]:
x ** x

array([[    1,     4,    27],
       [  256,  3125, 46656]])

▪ 배열 간의 곱셈에서는 요소별 연산과 벡터의 내적(dot product) 연산 가능  
- 벡터의 내적 : 두 배열 간의 곱셈  
- 두 개의 행렬에서 첫 번째 행렬의 열 크기와 두 번째 행렬의 행 크기가 동일해야 함  
- m×n 행렬과 n×l 행렬, 벡터의 내적 연산하면 m×l의 행렬 생성  

▪ dot 함수 : 벡터의 내적 연산

In [125]:
x_1 = np.arange(1, 7).reshape(2,3)
x_2 = np.arange(1, 7).reshape(3,2)
x_1

array([[1, 2, 3],
       [4, 5, 6]])

In [126]:
x_2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [127]:
x_1.dot(x_2)

array([[22, 28],
       [49, 64]])

▪ 브로드캐스팅 연산(broadcasting operations) : 하나의 행렬과 스칼라 값들 간의 연산이나 행렬과 벡터 간의 연산  
- 방송국의 전파가 퍼지듯 뒤에 있는 스칼라 값이 모든 요소에 퍼지듯이 연산

In [128]:
x = np.arange(1, 10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [129]:
x + 10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [130]:
x - 2

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [131]:
x // 3

array([[0, 0, 1],
       [1, 1, 2],
       [2, 2, 3]])

In [132]:
x ** 2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

- 행렬과 스칼라 값 외에 행렬과 벡터, 벡터와 벡터 간에도 연산

In [133]:
x = np.arange(1, 13).reshape(4,3)
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [134]:
v = np.arange(10 , 40 , 10)
v

array([10, 20, 30])

In [136]:
x + v

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

## 04 비교 연산과 데이터 추출

### 1. 비교 연산

▪ 연산 결과는 항상 불린형(boolean type)을 가진 배열로 추출

### 1.1 브로드캐스팅 비교 연산

▪ 하나의 스칼라 값과 벡터 간의 비교 연산은 벡터 내 전체 요소에 적용

In [138]:
import numpy as np

In [139]:
x = np.array([4, 3, 2, 6, 8, 5])
x > 3

array([ True, False, False,  True,  True,  True])

### 1.2 요소별 비교 연산

▪ 두 개의 배열 간 배열의 구조(shape)가 동일한 경우  
▪ 같은 위치에 있는 요소들끼리 비교 연산  
▪ [1 ＞ 2, 3 ＞ 1, 0 ＞ 7] 과 같이 연산이 실시된 후 이를 반환

In [140]:
x = np.array([1, 3, 0])
y = np.array([2, 1, 7])
x > y

array([False,  True, False])

### 2. 비교 연산 함수

### 2.1 all과 any

▪ all 함수 : 배열 내부의 모든 값이 참일 때는 True, 하나라도 참이 아닐 경우에는 False를 반환
- and 조건을 전체 요소에 적용

▪ any 함수 : 배열 내부의 값 중 하나라도 참일 때는 True, 모두 거짓일 경우 False를 반환
- or 조건을 전체 요소에 적용

In [141]:
x = np.array([4, 6, 7, 3, 2])
(x > 3)

array([ True,  True,  True, False, False])

In [142]:
(x > 3).all()

np.False_

In [143]:
(x > 3).any()

np.True_

In [144]:
(x < 10).any()

np.True_

In [146]:
(x < 10).all()

np.True_

In [147]:
(x > 10).any()

np.False_

### 2.2 인덱스 반환 함수

▪ where 함수 : 배열이 불린형으로 이루어졌을 때 참인 값들의 인덱스를 반환

In [148]:
x = np.array([4, 6, 7, 3, 2])
x > 5

array([False,  True,  True, False, False])

In [150]:
np.where(x>5) # 6과 7의 인덱스 값인 [1, 2]를 반환

(array([1, 2]),)

    - True/False 대신 참/거짓인 경우의 값을 지정할 수 있음

In [152]:
x = np.array([4, 6, 7, 3, 2])
np.where(x>5 , 10, 20) # 참일 경우에 10을, 거짓일 경우에 20을 반환

array([20, 10, 10, 20, 20])

### 2.3 정렬된 값의 인덱스를 반환해주는 함수

▪ argsort : 배열 내 값들을 작은 순서대로 인덱스를 반환  
▪ argmax : 배열 내 값들 중 가장 큰 값의 인덱스를 반환  
▪ argmin : 배열 내 값들 중 가장 작은 값의 인덱스를 반환

In [153]:
x = np.array([4, 6, 7, 3, 2])
np.argsort(x)

array([4, 3, 0, 1, 2])

In [154]:
np.argmax(x)

np.int64(2)

In [155]:
np.argmin(x)

np.int64(4)

## 3. 인덱스를 활용한 데이터 추출

### 3.1 불린 인덱스

▪ 불린 인덱스(boolean index) : 배열에 있는 값들을 반환할 특정 조건을 불린형의 배열에 넣어서 추출  
- 인덱스에 들어가는 배열은 불린형이어야 함  
- 불린형 배열과 추출 대상이 되는 배열의 구조가 같아야 함

In [156]:
x = np.array([4, 6, 7, 3, 2])
x > 3

array([ True,  True,  True, False, False])

In [157]:
cond = x > 3
x[cond]

array([4, 6, 7])

In [158]:
x.shape

(5,)

In [159]:
cond.shape

(5,)

### 3.2 팬시 인덱스

▪ 팬시 인덱스(fancy index) : 정수형 배열의 값을 사용하여 해당 정수의 인덱스에 위치한 값을 반환  
- 인덱스 항목에 넣을 배열은 정수로만 구성되어야 함
- 정수 값의 범위는 대상이 되는 배열이 가지는 인덱스의 범위내 대상이 되는 배열과 인덱스 배열의 구조(shape)가 같을 필요는 없음

In [160]:
x = np.array([4, 6, 7, 3, 2])
cond = np.array([1, 2, 0, 2, 2, 2,], int)
x[cond]

array([6, 7, 4, 7, 7, 7])

In [161]:
x.take(cond)

array([6, 7, 4, 7, 7, 7])

In [163]:
x = np.array([[1,4], [9,16]], int)
a = np.array([0, 1, 1, 1, 0, 0], int)
b = np.array([0, 0, 0, 1, 1, 1], int)
x[a,b]

array([ 1,  9,  9, 16,  4,  4])