# ch03 numpy (1)

1. 0~19 의 정수를 만들고,이것을 (2 x 5 x 2) 3차원 배열을 만들고 출력하시오.
2. 1번에서 만든것을 4  x5 배열로 만들고 출력하시오. 
3. 1번에서 만든것을 1차원 배열로 만들고 출력하시오. 

In [1]:
import numpy as np

In [5]:
# 1. 0~19까지의 정수를 생성하고 (2x5x2) 3차원 배열로 변환
arr = np.arange(20).reshape(2, 5, 2)
print(arr)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


In [6]:
# 2. 3차원 배열을 (4x5) 2차원 배열로 변환
arr_2d = arr.reshape(4, 5)
print(arr_2d)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [7]:
# 3. 3차원 배열을 1차원 배열로 변환
arr_1d = arr.flatten()
print(arr_1d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


# ch03 numpy (2)

1. 공정한 주사위를 만들어 10번 던질때의 각 번호의 출현회수를 출력하라.
2. 공정한 주사위를 만들어 1000번 던질때의 각 번호의 출현회수를 출력하라.
단, 균등분포(uniform) 를 이용하여 하라. 

In [18]:
import numpy as np

In [19]:
import numpy as np

def roll_dice(n):
    rolls = np.random.uniform(1, 7, n).astype(int)  # 1~6 사이의 난수 생성
    result = {}  # 빈 딕셔너리 생성

    # 출현 횟수 계산
    for num in rolls:
        if num in result:
            result[num] += 1
        else:
            result[num] = 1

    return result

In [20]:
# 1. 10번 던지기
print("10번 던진 결과:", roll_dice(10))

10번 던진 결과: {np.int64(6): 1, np.int64(2): 2, np.int64(1): 2, np.int64(4): 3, np.int64(3): 1, np.int64(5): 1}


In [21]:
# 2. 1000번 던지기
print("1000번 던진 결과:", roll_dice(1000))

1000번 던진 결과: {np.int64(1): 182, np.int64(3): 145, np.int64(4): 166, np.int64(6): 169, np.int64(2): 166, np.int64(5): 172}


# ch03 numpy (3)

np.argmax를 이용하여 다음 배열의 최대값을 출력하라.   
a = [2,3,5,8,1,0]

In [25]:
import numpy as np

In [26]:
a = np.array([2,3,5,8,1,0], int)
max_index = np.argmax(a)
a[max_index]

np.int64(8)